# Generated by Django 5.0.3 on 2024-03-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_unit_alter_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='unit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
