# Generated by Django 5.0.3 on 2024-03-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_purchasebill_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendtokitchen',
            name='unit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
