# Generated by Django 5.0.3 on 2024-03-18 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_sales'),
        ('vendor', '0002_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
