# Generated by Django 5.0.3 on 2024-03-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_receipe_name_receipe_quantity_receipe_unit_menuitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='receipe',
            field=models.ManyToManyField(null=True, to='menus.receipe'),
        ),
    ]
