# Generated by Django 5.0.3 on 2024-03-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_menuitem_receipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='receipe',
            field=models.ManyToManyField(to='menus.receipe'),
        ),
    ]
