# Generated by Django 5.0.3 on 2024-03-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_alter_menuitem_receipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
