# Generated by Django 5.0.3 on 2024-03-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_alter_menuitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
