# Generated by Django 5.0.3 on 2024-03-17 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.table'),
        ),
    ]
